# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models.
name: "my_new_project"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# The directory which will store compiled SQL files.
target-path: "target"

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  # Global model configurations
  +transient: false  # Ensure models are not transient by default

  # Configuration for your project models
  my_new_project:
    
    # Staging models configuration
    staging:
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"  # Use environment variable for dynamic database naming
      google_sheets:
        +schema: google_sheets  # Schema for google_sheets source
      sql_server_dbo:
        +schema: sql_server_dbo  # Schema for sql_server_dbo source

    # Marts models configuration
    marts:
      +database: "{{ env_var('DBT_ENVIRONMENTS') }}_GOLD_DB"  # Dynamic database name for marts
      core:
        +schema: core  # Core schema for marts models

# Seeds configuration
seeds:
  +schema: seed_data  # Schema for seeds
  +database: "{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB"  # Use environment variable for dynamic seed database

# Snapshots configuration
snapshots:
  +transient: false  # Ensure snapshots are not transient
  +target_database: "{{ env_var('DBT_ENVIRONMENTS') }}_SILVER_DB"  # Target database for snapshots
  +target_schema: snapshots  # Target schema for snapshots
